### ISSUE TITLE
[Forge][mc1.19-v2.0.2][Server] Mod uses library that is not loaded on dedicated Forge server

### ISSUE THREAD

**Issue by TigerWalts** [SteveKunG/FishOfThieves#12]
Mod Version: mc1.19-v2.0.2
Forge Version:  1.19-41.0.62

The mod uses the `org/apache/commons/compress/utils/Lists` class when registering loot tables and villager trades.

This class is not loaded by dedicated Forge servers and so servers crash when these events are triggered.

- https://github.com/SteveKunG/FishOfThieves/blob/9fbd04c93331e0d8bc5afd0aac1e2e31df2fe97c/forge/src/main/java/com/stevekung/fishofthieves/forge/proxy/CommonProxyForge.java

<details>
  <summary>Error from log - Click to expand</summary>

```
[01Jul2022 14:05:23.166] [main/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: org/apache/commons/compress/utils/Lists
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: com.stevekung.fishofthieves.forge.proxy.CommonProxyForge@7739a0a0 registerLootTables(Lnet/minecraftforge/event/LootTableLoadEvent;)V
                2: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@12b5a275 onChestGenerated(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
        at TRANSFORMER/fishofthieves@2.0.2/com.stevekung.fishofthieves.forge.proxy.CommonProxyForge.registerLootTables(CommonProxyForge.java:118)
        at TRANSFORMER/fishofthieves@2.0.2/com.stevekung.fishofthieves.forge.proxy.__CommonProxyForge_registerLootTables_LootTableLoadEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@41.0.62/net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:581)
        at TRANSFORMER/forge@41.0.62/net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:798)
        at TRANSFORMER/minecraft@1.19/net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTables.java:41)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at TRANSFORMER/minecraft@1.19/net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:38)
        at TRANSFORMER/minecraft@1.19/net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:16)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
        at TRANSFORMER/minecraft@1.19/net.minecraft.Util.m_214652_(Util.java:774)
        at TRANSFORMER/minecraft@1.19/net.minecraft.Util.m_214679_(Util.java:763)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.Main.main(Main.java:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19-41.0.62/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.1/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at cpw.mods.securejarhandler@2.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at cpw.mods.securejarhandler@2.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 31 more
```

</details>

**Comment by SteveKunG** [comment]
Fixed in 2.0.3.
